apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filegator-pvc
  namespace: filegator
spec:
  storageClassName: default-sc
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 50Gi } }
